### ISSUE TITLE
A default Map[Int,X] format is available at compile time, but fails at runtime

### ISSUE THREAD

**Issue by acruise** [spray/spray-json#125]
```
scala> import spray.json._
scala> import spray.json.DefaultJsonProtocol._
scala> val jf = implicitly[JsonFormat[Map[Int,String]]]
jf: spray.json.JsonFormat[Map[Int,String]] = spray.json.CollectionFormats$$anon$3@2de7fe0e

scala> jf.write(Map(1 -> "Foo"))
spray.json.SerializationException: Map key must be formatted as JsString, not '1'
  at spray.json.CollectionFormats$$anon$3$$anonfun$write$3.apply(CollectionFormats.scala:53)
  at spray.json.CollectionFormats$$anon$3$$anonfun$write$3.apply(CollectionFormats.scala:50)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at spray.json.CollectionFormats$$anon$3.write(CollectionFormats.scala:50)
  at spray.json.CollectionFormats$$anon$3.write(CollectionFormats.scala:48)
  ... 35 elided

scala> jf.read("""{"2": "Two"}""".parseJson)
spray.json.DeserializationException: Expected Int as JsNumber, but got "2"
  at spray.json.package$.deserializationError(package.scala:23)
  at spray.json.BasicFormats$IntJsonFormat$.read(BasicFormats.scala:29)
  at spray.json.BasicFormats$IntJsonFormat$.read(BasicFormats.scala:25)
  at spray.json.JsValue.convertTo(JsValue.scala:31)
  at spray.json.CollectionFormats$$anon$3$$anonfun$read$3.apply(CollectionFormats.scala:59)
  at spray.json.CollectionFormats$$anon$3$$anonfun$read$3.apply(CollectionFormats.scala:58)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
  at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
  at scala.collection.AbstractTraversable.map(Traversable.scala:104)
  at spray.json.CollectionFormats$$anon$3.read(CollectionFormats.scala:60)
  at spray.json.CollectionFormats$$anon$3.read(CollectionFormats.scala:48)
  ... 35 elided
```

**Comment by maciejjaskowski** [comment]
This is not a bug, this is JSON: http://json.org/

**Comment by acruise** [comment]
@maciejjaskowski, the bug is that Spray will find a format at compile time that cannot possibly succeed at runtime. :)

**Comment by initialcontext** [comment]
Any movement on this? I have encountered the same issue with spray-json_2.10 v1.3.2 when serializing or deserializing maps with non-String keys

**Comment by minisaw** [comment]
so annoying not being able to serialize non-String keyed maps.

**Comment by kardapoltsev** [comment]
+1

**Comment by hopkirk** [comment]
+1

**Comment by blbarker** [comment]
+1

**Comment by ppiotrow** [comment]
+1

**Comment by wlk** [comment]
I stumbled on the same bug just now, this is my approach to reproduce: https://github.com/wlk/spray-serialization-bug/blob/master/src/main/scala/Main.scala

**Comment by fmarmann** [comment]
+1

**Comment by satyagraha** [comment]
If I copy the code from https://github.com/ancane/spray-json/commit/0b6c60030c169fabbae9fe434fd23d0506944abd into my source and have it visible at implicit resolution time, then it gets picked up OK. If using IntelliJ I found I had to rebuild my entire project as it seems to cache stuff.

**Comment by janjaali** [comment]
I just tried to resolve the issue and improve the extensibility of the Map format <https://github.com/spray/spray-json/pull/331>. It would be kind if you would take a look at it :)
