### ISSUE TITLE
Fix automatic field name discovery for member names with mangled prefix

### ISSUE THREAD

**Issue by kaushikrroy** [spray/spray-json#142]
I have a use case where in I need to parse JSON like:  '{"-id": 123 , "id" : 234 }'. I have modelled it to the following code (sample):

```Scala
package test.spray.json

import spray.json.DefaultJsonProtocol
import spray.json.JsonParser
import spray.json.ParserInput.apply
import java.lang.reflect.Modifier

object TestObjectModel {
  case class SomeObject(val `-id`: Int, val id: Int)

  object SomeObjectProtocol extends DefaultJsonProtocol {
    implicit val someObjFormat = jsonFormat2(SomeObject)
  }

  def main(args: Array[String]): Unit = {
//    From: spray.json.ProductFormats.extractFieldNames():
//    ==============================================================================================================     
//        classOf[SomeObject].getDeclaredFields.filterNot { f ⇒
//          f.getName.startsWith("$") || Modifier.isTransient(f.getModifiers) || Modifier.isStatic(f.getModifiers)
//        }
//     =============================================================================================================    
//      The above does not count `-id` as a field, cause it gets generated as $minusid.    
//      Add support for names such as: $minusid, $at, $hash etc..?
    
    import TestObjectModel.SomeObjectProtocol._
    val json = """{"-id": 123 , "id" : 234 } """
    JsonParser(json).convertTo[SomeObject]
  }
}
```
But I am not able to parse and convert it to <code>SomeObject</code>, I get the following exception:

```java
Exception in thread "main" java.lang.ExceptionInInitializerError
	at test.spray.json.TestObjectModel$.main(TestObjectModel.scala:30)
	at test.spray.json.TestObjectModel.main(TestObjectModel.scala)
Caused by: java.lang.RuntimeException: Cannot automatically determine case class field names and order for 'test.spray.json.TestObjectModel$SomeObject', please use the 'jsonFormat' overload with explicit field name specification
	at spray.json.ProductFormats$class.extractFieldNames(ProductFormats.scala:83)
	at test.spray.json.TestObjectModel$SomeObjectProtocol$.extractFieldNames(TestObjectModel.scala:14)
	at spray.json.ProductFormatsInstances$class.jsonFormat2(ProductFormatsInstances.scala:43)
	at test.spray.json.TestObjectModel$SomeObjectProtocol$.jsonFormat2(TestObjectModel.scala:14)
	at test.spray.json.TestObjectModel$SomeObjectProtocol$.<init>(TestObjectModel.scala:15)
	at test.spray.json.TestObjectModel$SomeObjectProtocol$.<clinit>(TestObjectModel.scala)
	... 2 more
Caused by: java.lang.RuntimeException: Case class test.spray.json.TestObjectModel$SomeObject declares additional fields
	at scala.sys.package$.error(package.scala:27)
	at spray.json.ProductFormats$class.extractFieldNames(ProductFormats.scala:78)
	... 7 more
```
Is my observation valid? Version of spray-json I am using is the following:
```Scala
"io.spray" % "spray-json_2.11" % "1.3.1"
```

**Comment by sirthias** [comment]
Have you seen this exception message?:

> Cannot automatically determine case class field names and order for 'test.spray.json.TestObjectModel$SomeObject’,
> please use the 'jsonFormat' overload with explicit field name specification

Cheers,
Mathias

---
mathias@spray.io
http://spray.io

**Comment by sirthias** [comment]
I have changed the title to better reflect the improvement request.
Thanks for reporting!

**Comment by kaushikrroy** [comment]
Thanks a ton for the title correction, my bad, and I am already using the 'jsonFormat' overload with explicit field name specification to continue with my development. I feel it would be a good improvement to have, these cases handled. Thanks a ton. Spray is a great framework, we love it.

**Comment by sirthias** [comment]
Great to hear! Thanks!
