### ISSUE TITLE
JVM crashing with spray-json 1.3.1

### ISSUE THREAD

**Issue by doubaokun** [spray/spray-json#145]
Version:

    "io.spray"            %%  "spray-can"     % "1.3.2",
    "io.spray"            %%  "spray-routing" % "1.3.2",
    "io.spray"            %%  "spray-json" % "1.3.1",

crashing when:

  post {
          entity(as[XXXX]) { xx =>

	java.lang.NoSuchMethodError: spray.json.JsonParser$.apply(Ljava/lang/String;)Lspray/json/JsValue;
		at spray.httpx.SprayJsonSupport$$anonfun$sprayJsonUnmarshaller$1.applyOrElse(SprayJsonSupport.scala:36)
		at spray.httpx.SprayJsonSupport$$anonfun$sprayJsonUnmarshaller$1.applyOrElse(SprayJsonSupport.scala:34)
		at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
		at spray.httpx.unmarshalling.Unmarshaller$$anon$1$$anonfun$unmarshal$1.apply(Unmarshaller.scala:29)
		at spray.httpx.unmarshalling.SimpleUnmarshaller.protect(SimpleUnmarshaller.scala:40)
		at spray.httpx.unmarshalling.Unmarshaller$$anon$1.unmarshal(Unmarshaller.scala:29)
		at spray.httpx.unmarshalling.SimpleUnmarshaller.apply(SimpleUnmarshaller.scala:29)
		at spray.httpx.unmarshalling.SimpleUnmarshaller.apply(SimpleUnmarshaller.scala:23)
		at spray.httpx.unmarshalling.UnmarshallerLifting$$anon$3.apply(UnmarshallerLifting.scala:35)
		at spray.httpx.unmarshalling.UnmarshallerLifting$$anon$3.apply(UnmarshallerLifting.scala:34)
		at spray.httpx.unmarshalling.UnmarshallerLifting$$anon$1.apply(UnmarshallerLifting.scala:25)
		at spray.httpx.unmarshalling.UnmarshallerLifting$$anon$1.apply(UnmarshallerLifting.scala:24)
		at spray.httpx.unmarshalling.package$PimpedHttpRequest.as(package.scala:47)
		at spray.routing.directives.MarshallingDirectives$$anonfun$entity$1.apply(MarshallingDirectives.scala:35)
		at spray.routing.directives.MarshallingDirectives$$anonfun$entity$1.apply(MarshallingDirectives.scala:35)
		at spray.routing.directives.BasicDirectives$$anonfun$extract$1.apply(BasicDirectives.scala:86)
		at spray.routing.directives.BasicDirectives$$anonfun$extract$1.apply(BasicDirectives.scala:86)
		at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
		at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
		at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
		at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
		at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
		at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
		at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
		at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30)
		at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
		at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92)
		at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32)
		at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31)
		at spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130)
		at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
		at spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84)

**Comment by sirthias** [comment]
NoSuchMethodErrors are almost always a "wrong dependency version" problem.
In your case upgrading *spray-can* and *spray-routing* to 1.3.3 should do the trick.
