### ISSUE TITLE
Error building a codec for a value class

### ISSUE THREAD

**Issue by TimurFayruzov** [spray/spray-json#185]
```
case class InstanceId(value: String) extends AnyVal

object Explore extends App {

  import spray.json._
  import DefaultJsonProtocol._

  implicit val codec = jsonFormat1(InstanceId)

  println(InstanceId("id").toJson)
}
```

throws the following:
```
Exception in thread "main" java.lang.RuntimeException: Cannot automatically determine case class field names and order for 'com.hiya.protocol.InstanceId', please use the 'jsonFormat' overload with explicit field name specification
	at spray.json.ProductFormats$class.extractFieldNames(ProductFormats.scala:84)
	at spray.json.DefaultJsonProtocol$.extractFieldNames(DefaultJsonProtocol.scala:30)
	at spray.json.ProductFormatsInstances$class.jsonFormat1(ProductFormatsInstances.scala:23)
	at spray.json.DefaultJsonProtocol$.jsonFormat1(DefaultJsonProtocol.scala:30)
	at com.mytest.Explore$.delayedEndpoint$com$hiya$protocol$Explore$1(Explore.scala:10)
	at com.mytest.Explore$delayedInit$body.apply(Explore.scala:5)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.mytest.Explore$.main(Explore.scala:5)
	at com.mytest.Explore.main(Explore.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NumberFormatException: For input string: "1$extension"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
	at spray.json.ProductFormats$$anonfun$2.apply(ProductFormats.scala:73)
	at spray.json.ProductFormats$$anonfun$2.apply(ProductFormats.scala:73)
	at scala.math.Ordering$$anon$5.compare(Ordering.scala:122)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1438)
	at scala.collection.SeqLike$class.sorted(SeqLike.scala:648)
	at scala.collection.mutable.ArrayOps$ofRef.sorted(ArrayOps.scala:186)
	at scala.collection.SeqLike$class.sortBy(SeqLike.scala:623)
	at scala.collection.mutable.ArrayOps$ofRef.sortBy(ArrayOps.scala:186)
	at spray.json.ProductFormats$class.extractFieldNames(ProductFormats.scala:72)
	... 19 more
```

**Comment by moguzhanataman** [comment]
This works, if you still need it: 
```scala
case class InstanceId(value: String)

import spray.json.DefaultJsonProtocol

object Explore extends DefaultJsonProtocol {
  implicit val codec = jsonFormat1(InstanceId)
}

import Explore._
import spray.json._

println(InstanceId("id").toJson)
```
