### ISSUE TITLE
Base class inheritance issue

### ISSUE THREAD

**Issue by huntc** [spray/spray-json#250]
If a class inherits fields from a base class, then spray-json throws an error. An example to illustrate:

```scala
class A(val w: Int)

case class B(override val w: Int) extends A(w)

val a: A = B(1)

// Let's do some JSON

import spray.json._

object AJsonProtocol extends DefaultJsonProtocol {

  import BJsonProtocol._
  
  implicit val aFormat: RootJsonFormat[A] = new RootJsonFormat[A] {

    override def read(json: JsValue): A =
      json.convertTo[B]

    override def write(obj: A): JsValue =
      obj.asInstanceOf[B].toJson
  }
}

object BJsonProtocol extends DefaultJsonProtocol {
  implicit val bFormat: JsonFormat[B] =
    jsonFormat1(B)
}

import AJsonProtocol._

a.toJson
```

The above can be pasted when in sbt's `console` mode for a project that has spray-json on the path. The code produces the following error:

```
java.lang.RuntimeException: Cannot automatically determine case class field names and order for 'B', please use the 'jsonFormat' overload with explicit field name specification
  at spray.json.ProductFormats.extractFieldNames(ProductFormats.scala:85)
```

The console doesn't provide the full output, but at runtime, this is the cause as output by my program:

```
Caused by: java.lang.NumberFormatException: For input string: "1$extension"
  at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  at java.base/java.lang.Integer.parseInt(Integer.java:652)
  at java.base/java.lang.Integer.parseInt(Integer.java:770)
  at scala.collection.immutable.StringLike.toInt(StringLike.scala:301)
  at scala.collection.immutable.StringLike.toInt$(StringLike.scala:301)
  at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
  at spray.json.ProductFormats.$anonfun$extractFieldNames$2(ProductFormats.scala:73)
```

I shall investigate further, but at first glance, it appears that the following spray-json code isn't expecting the `1$extension` suffix:

```scala
      val copyDefaultMethods = clazz.getMethods.filter(_.getName.startsWith("copy$default$")).sortBy(
        _.getName.drop("copy$default$".length).takeWhile(_ != '(').toInt)
```

Any thoughts?

**Comment by huntc** [comment]
I'm closing this out as I may have been looking at two different things. Firstly, it appears that additional fields in a case class are not catered for and that's quite explicit. Secondly, I still don't know where the `$extension` suffix is coming from, or what causes that, but it may have had something to do with using value types. The latter are preferred to be explicitly formatted, so I've "worked around" the issue.
