### ISSUE TITLE
NullPointerException when passing null to JsString

### ISSUE THREAD

**Issue by martin-g** [spray/spray-json#70]
Hi,

This is my first use of Spray-Json so I didn't know its rules to handle null values.

I want to serialize a non-case class (Hibernate entity). The code looks like:

``` scala
implicit object EntityJsonFormat extends RootJsonFormat[Entity] {
    def write(e: Entity) = {
      JsObject(
        "id" -> JsNumber(e.id),
        "name" -> JsString(e.name),
        "desc" -> JsString(e.optional) // this may be null
      )
    }
```

And it fails with:

```
2013-08-25 16:03:33,513 [test-akka.actor.default-dispatcher-2] ERROR [akka.actor.RepointableActorRef] - Error during processing of request HttpRequest(GET,http://localhost:8080/test,List(Host: localhost:8080, Authorization: Basic bWFydGluLmdyaWdvcm92QGp3ZWVrZW5kLmNvbTphc2Rm, User-Agent: curl/7.29.0),EmptyEntity,HTTP/1.1)
java.lang.NullPointerException: null
    at spray.json.JsonPrinter$class.firstToBeEncoded$1(JsonPrinter.scala:60) ~[spray-json_2.10-1.2.5.jar:1.2.5]
    at spray.json.JsonPrinter$class.printString(JsonPrinter.scala:63) ~[spray-json_2.10-1.2.5.jar:1.2.5]
    at spray.json.PrettyPrinter$.printString(PrettyPrinter.scala:68) ~[spray-json_2.10-1.2.5.jar:1.2.5]
    at spray.json.JsonPrinter$class.printLeaf(JsonPrinter.scala:52) ~[spray-json_2.10-1.2.5.jar:1.2.5]
    at spray.json.PrettyPrinter$.printLeaf(PrettyPrinter.scala:68) ~[spray-json_2.10-1.2.5.jar:1.2.5]
    at spray.json.PrettyPrinter$class.spray$json$PrettyPrinter$$print(PrettyPrinter.scala:36) ~[spray-json_2.10-1.2.5.jar:1.2.5]
    at spray.json.PrettyPrinter$$anonfun$printObject$2.apply(PrettyPrinter.scala:46) ~[spray-json_2.10-1.2.5.jar:1.2.5]
    at spray.json.PrettyPrinter$$anonfun$printObject$2.apply(PrettyPrinter.scala:42) ~[spray-json_2.10-1.2.5.jar:1.2.5]
    at spray.json.JsonPrinter$$anonfun$printSeq$1.apply(JsonPrinter.scala:94) ~[spray-json_2.10-1.2.5.jar:1.2.5]
    at spray.json.JsonPrinter$$anonfun$printSeq$1.apply(JsonPrinter.scala:92) ~[spray-json_2.10-1.2.5.jar:1.2.5]
    at scala.collection.Iterator$class.foreach(Iterator.scala:727) ~[scala-library-2.10.2.jar:na]
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157) ~[scala-library-2.10.2.jar:na]
....
```

To overcome this NPE I changed my code to:

``` scala
implicit object EntityJsonFormat extends RootJsonFormat[Entity] {
    def write(e: Entity) = {
      val optJs =
        if (e.optional != null) JsString(e.optional)
        else JsNull
      JsObject(
        "id" -> JsNumber(e.id),
        "name" -> JsString(e.name),
        "desc" -> optJs
      )
    }
```

I have two suggestions:
1) add require(arg != null) in JsString#apply(String) (and other JsValue impls)
2) or degrade JsString(null) automatically to JsNull

In any case the NPE should not happen.

**Comment by initialcontext** [comment]
I have been using Spray-Json and having some trouble with this too. While I agree that one could argue null values have no place in a Scala library, handling them in a reasonable way (especially for parsing incoming JSON into Scala where some values in the JSON could be null) should not fail or NPE since we have no guarantees when reading JSON about which language wrote the data or how it handles nulls.

I have been having a frustrating time porting some of my code to Spray-Json when it cannot read reasonable incoming Map[String, String] data serialized by another library from a language where nulls are appropriate.

Changing external services around to match Spray's expectations seems silly just to get external JSON data into my Scala code. Could we handle this case (incoming JSON needing to be deserialized) a bit differently?

**Comment by maasg** [comment]
There is an argument about protecting or not against `null` in a Scala API. The actual problem with this bug is that it's completely obscure where the error comes from. 
I spent a good part of my day trying to discover, first, why I was having this error after I had built the JSON and second, where the `null` was coming from.
A `JsString(null) ` creates an illegal state in the internal representation. Constructing the JSON object won't fail but you can't use the JSON AST that results of it.
In my opinion, that is the most pressing issue.

**Comment by ktoso** [comment]
Not sure why the comment in this 3 years old ticket; what action are you requesting / suggesting @maasg ?

PRs welcome
